apiVersion: 1

datasources:
  - name: Oracle Analytics
    type: simplejson
    access: proxy
    url: http://oracle-proxy:5000
    isDefault: true
    jsonData:
      httpMethod: POST
    secureJsonData: {}
    editable: true