# Terraform equivalent of free-tier-edge-cloud.sh
# This recreates your bash script setup in infrastructure-as-code

# SNS Topic for edge alerts
resource "aws_sns_topic" "edge_alerts" {
  name = "edge-alerts"

  tags = {
    Name        = "Edge Alerts Topic"
    Project     = var.project_name
    Environment = "production"
    ManagedBy   = "terraform"
  }
}

# CloudWatch dashboard for edge metrics
resource "aws_cloudwatch_dashboard" "edge_cluster" {
  dashboard_name = "EdgeCluster"

  dashboard_body = jsonencode({
    widgets = [
      {
        type   = "metric"
        x      = 0
        y      = 0
        width  = 12
        height = 6

        properties = {
          metrics = [
            ["EdgeCluster", "CPUUtilization", "Device", "pifive0"],
            [".", ".", "Device", "piiv"],
            [".", ".", "Device", "piiv2"]
          ]
          view    = "timeSeries"
          stacked = false
          region  = var.aws_region
          title   = "Edge Device CPU Utilization"
          period  = 300
        }
      },
      {
        type   = "metric"
        x      = 0
        y      = 6
        width  = 12
        height = 6

        properties = {
          metrics = [
            ["EdgeCluster", "MemoryUtilization", "Device", "pifive0"],
            [".", ".", "Device", "piiv"],
            [".", ".", "Device", "piiv2"]
          ]
          view    = "timeSeries"
          stacked = false
          region  = var.aws_region
          title   = "Edge Device Memory Utilization"
          period  = 300
        }
      }
    ]
  })
}

# CloudWatch alarm for high CPU usage
resource "aws_cloudwatch_metric_alarm" "high_cpu" {
  for_each = toset(["pifive0", "piiv", "piiv2"])
  
  alarm_name          = "edge-high-cpu-${each.value}"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = "2"
  metric_name         = "CPUUtilization"
  namespace           = "EdgeCluster"
  period              = "300"
  statistic           = "Average"
  threshold           = "80"
  alarm_description   = "This metric monitors cpu utilization for ${each.value}"

  dimensions = {
    Device = each.value
  }

  alarm_actions = [aws_sns_topic.edge_alerts.arn]

  tags = {
    Name        = "High CPU - ${each.value}"
    Project     = var.project_name
    Environment = "production"
    ManagedBy   = "terraform"
  }
}

# Fix the DynamoDB table to match your actual schema
resource "aws_dynamodb_table" "edge_device_state_corrected" {
  name           = "edge-device-state-v2"
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "deviceId"
  range_key      = "timestamp"

  attribute {
    name = "deviceId"
    type = "S"
  }

  attribute {
    name = "timestamp"
    type = "N"
  }

  tags = {
    Name        = "Edge Device State V2"
    Project     = var.project_name
    Environment = "production"
    ManagedBy   = "terraform"
  }
}

# Updated Lambda function with correct dependencies
resource "aws_lambda_function" "edge_processor_v2" {
  filename         = "edge-processor-v2.zip"
  function_name    = "edge-data-processor-v2"
  role            = aws_iam_role.lambda_edge_processor_role.arn
  handler         = "index.handler"
  runtime         = "nodejs18.x"
  timeout         = 30
  memory_size     = 128

  environment {
    variables = {
      DYNAMODB_TABLE = aws_dynamodb_table.edge_device_state_corrected.name
      SNS_TOPIC_ARN  = aws_sns_topic.edge_alerts.arn
    }
  }

  tags = {
    Name        = "Edge Data Processor V2"
    Project     = var.project_name
    Environment = "production"
    ManagedBy   = "terraform"
  }
}

# Local file for edge metrics script
resource "local_file" "push_metrics_script" {
  filename = "/tmp/terraform-push-metrics.sh"
  
  content = <<-EOF
#!/bin/bash
# Push edge metrics to CloudWatch (generated by Terraform)
# Only push critical metrics to stay under 10 custom metrics

NAMESPACE="EdgeCluster"
DEVICE=$(hostname)

# CPU usage
CPU=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | cut -f1 -d'%')
aws cloudwatch put-metric-data \
    --namespace $NAMESPACE \
    --metric-name CPUUtilization \
    --value $CPU \
    --dimensions Device=$DEVICE

# Memory usage  
MEM=$(free | grep Mem | awk '{print ($3/$2) * 100.0}')
aws cloudwatch put-metric-data \
    --namespace $NAMESPACE \
    --metric-name MemoryUtilization \
    --value $MEM \
    --dimensions Device=$DEVICE
EOF

  file_permission = "0755"
}

# Output the path to the metrics script
output "metrics_script_path" {
  description = "Path to the generated edge metrics script"
  value       = local_file.push_metrics_script.filename
}