-- Cloud Cost Analytics Schema for Oracle Database
-- Optimized for performance with indexed metrics columns
-- Author: Cloud Operations System
-- Date: 2025-07-26

-- Drop existing objects if needed (be careful in production!)
-- DROP TABLE CLOUD_COMPARE.WORKFLOW_EXECUTIONS;
-- DROP TABLE CLOUD_COMPARE.COST_ANOMALIES;
-- DROP MATERIALIZED VIEW CLOUD_COMPARE.MV_DAILY_COST_SUMMARY;
-- DROP TABLE CLOUD_COMPARE.COST_DAILY_METRICS;

-- Main metrics table with indexed numeric columns for performance
CREATE TABLE CLOUD_COMPARE.COST_DAILY_METRICS (
    metric_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recorded_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    service_name VARCHAR2(100) NOT NULL,
    device_id VARCHAR2(100),
    daily_cost NUMBER(10,2) NOT NULL,
    
    -- Indexed numeric columns for critical metrics
    cpu_usage_avg NUMBER(5,2),
    cpu_usage_peak NUMBER(5,2),
    memory_usage_avg NUMBER(5,2),
    memory_usage_peak NUMBER(5,2),
    disk_usage_pct NUMBER(5,2),
    network_bytes_total NUMBER(20),
    
    -- Flexible JSON for additional metrics
    metric_data CLOB CHECK (metric_data IS JSON),
    
    -- Partitioning key for performance
    metric_date DATE GENERATED ALWAYS AS (TRUNC(recorded_at)) VIRTUAL
) 
PARTITION BY RANGE (metric_date) 
INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(PARTITION p_initial VALUES LESS THAN (DATE '2025-01-01'));

-- Indexes for query performance
CREATE INDEX idx_metrics_date_service ON CLOUD_COMPARE.COST_DAILY_METRICS(metric_date, service_name);
CREATE INDEX idx_metrics_device_date ON CLOUD_COMPARE.COST_DAILY_METRICS(device_id, metric_date);
CREATE INDEX idx_metrics_cpu_peak ON CLOUD_COMPARE.COST_DAILY_METRICS(cpu_usage_peak);

-- Anomalies table with severity index
CREATE TABLE CLOUD_COMPARE.COST_ANOMALIES (
    anomaly_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detected_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    anomaly_type VARCHAR2(50) NOT NULL,
    severity VARCHAR2(20) CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')),
    service_name VARCHAR2(100),
    device_id VARCHAR2(100),
    current_value NUMBER(10,2),
    expected_value NUMBER(10,2),
    variance_pct NUMBER(5,2) GENERATED ALWAYS AS 
        (ROUND(((current_value - expected_value) / NULLIF(expected_value, 0)) * 100, 2)) VIRTUAL,
    details CLOB CHECK (details IS JSON),
    resolved_at TIMESTAMP(6),
    resolution_notes VARCHAR2(4000)
);

CREATE INDEX idx_anomaly_severity_date ON CLOUD_COMPARE.COST_ANOMALIES(severity, detected_at);
CREATE INDEX idx_anomaly_unresolved ON CLOUD_COMPARE.COST_ANOMALIES(resolved_at) 
    WHERE resolved_at IS NULL;

-- Create materialized view log for fast refresh
CREATE MATERIALIZED VIEW LOG ON CLOUD_COMPARE.COST_DAILY_METRICS
    WITH ROWID, PRIMARY KEY (metric_date, service_name, daily_cost, cpu_usage_avg, cpu_usage_peak, memory_usage_avg, memory_usage_peak)
    INCLUDING NEW VALUES;

-- Aggregated daily summary for fast dashboards
CREATE MATERIALIZED VIEW CLOUD_COMPARE.MV_DAILY_COST_SUMMARY
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
AS
SELECT 
    metric_date,
    service_name,
    COUNT(*) as record_count,
    SUM(daily_cost) as total_cost,
    AVG(cpu_usage_avg) as avg_cpu,
    MAX(cpu_usage_peak) as max_cpu,
    AVG(memory_usage_avg) as avg_memory,
    MAX(memory_usage_peak) as max_memory
FROM CLOUD_COMPARE.COST_DAILY_METRICS
GROUP BY metric_date, service_name;

-- Workflow execution history
CREATE TABLE CLOUD_COMPARE.WORKFLOW_EXECUTIONS (
    execution_id VARCHAR2(100) PRIMARY KEY,
    workflow_name VARCHAR2(100) NOT NULL,
    started_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP(6),
    status VARCHAR2(20) CHECK (status IN ('Running', 'Success', 'Failed', 'Timeout')),
    anomalies_detected NUMBER DEFAULT 0,
    recommendations_generated NUMBER DEFAULT 0,
    potential_savings NUMBER(10,2),
    execution_details CLOB CHECK (execution_details IS JSON),
    error_message VARCHAR2(4000)
);

CREATE INDEX idx_workflow_status_date ON CLOUD_COMPARE.WORKFLOW_EXECUTIONS(status, started_at);

-- Real-time cost tracking view
CREATE OR REPLACE VIEW CLOUD_COMPARE.V_CURRENT_COSTS AS
SELECT 
    service_name,
    SUM(daily_cost) as today_cost,
    AVG(cpu_usage_avg) as avg_cpu_today,
    MAX(cpu_usage_peak) as peak_cpu_today,
    COUNT(DISTINCT device_id) as active_devices
FROM CLOUD_COMPARE.COST_DAILY_METRICS
WHERE metric_date = TRUNC(SYSDATE)
GROUP BY service_name;

-- 30-day trend view
CREATE OR REPLACE VIEW CLOUD_COMPARE.V_COST_TRENDS_30D AS
SELECT 
    metric_date,
    SUM(total_cost) as daily_total,
    LAG(SUM(total_cost), 1) OVER (ORDER BY metric_date) as previous_day,
    LAG(SUM(total_cost), 7) OVER (ORDER BY metric_date) as week_ago,
    ROUND(AVG(SUM(total_cost)) OVER (
        ORDER BY metric_date 
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ), 2) as rolling_7day_avg
FROM CLOUD_COMPARE.MV_DAILY_COST_SUMMARY
WHERE metric_date >= TRUNC(SYSDATE) - 30
GROUP BY metric_date;

-- Active anomalies view
CREATE OR REPLACE VIEW CLOUD_COMPARE.V_ACTIVE_ANOMALIES AS
SELECT 
    anomaly_id,
    anomaly_type,
    severity,
    service_name,
    device_id,
    current_value,
    expected_value,
    variance_pct,
    detected_at,
    EXTRACT(DAY FROM (SYSTIMESTAMP - detected_at)) * 24 + 
    EXTRACT(HOUR FROM (SYSTIMESTAMP - detected_at)) as hours_active
FROM CLOUD_COMPARE.COST_ANOMALIES
WHERE resolved_at IS NULL
ORDER BY 
    CASE severity 
        WHEN 'Critical' THEN 1
        WHEN 'High' THEN 2
        WHEN 'Medium' THEN 3
        WHEN 'Low' THEN 4
    END,
    detected_at DESC;

-- Grant permissions for application user
-- GRANT SELECT, INSERT, UPDATE ON CLOUD_COMPARE.COST_DAILY_METRICS TO <app_user>;
-- GRANT SELECT, INSERT, UPDATE ON CLOUD_COMPARE.COST_ANOMALIES TO <app_user>;
-- GRANT SELECT, INSERT, UPDATE ON CLOUD_COMPARE.WORKFLOW_EXECUTIONS TO <app_user>;
-- GRANT SELECT ON CLOUD_COMPARE.V_CURRENT_COSTS TO <app_user>;
-- GRANT SELECT ON CLOUD_COMPARE.V_COST_TRENDS_30D TO <app_user>;
-- GRANT SELECT ON CLOUD_COMPARE.V_ACTIVE_ANOMALIES TO <app_user>;

-- Initial test data
INSERT INTO CLOUD_COMPARE.COST_DAILY_METRICS (
    service_name, device_id, daily_cost, 
    cpu_usage_avg, cpu_usage_peak,
    memory_usage_avg, memory_usage_peak,
    disk_usage_pct, network_bytes_total,
    metric_data
) VALUES (
    'edge-devices', 'pifive0', 0.10,
    15.5, 45.2,
    32.1, 48.5,
    22.5, 1048576,
    '{"temperature": 42.3, "processes": 127}'
);

COMMIT;

-- Verify installation
SELECT 'Tables created:' as status, COUNT(*) as count 
FROM user_tables 
WHERE table_name IN ('COST_DAILY_METRICS', 'COST_ANOMALIES', 'WORKFLOW_EXECUTIONS');

SELECT 'Views created:' as status, COUNT(*) as count 
FROM user_views 
WHERE view_name IN ('V_CURRENT_COSTS', 'V_COST_TRENDS_30D', 'V_ACTIVE_ANOMALIES');

SELECT 'Test record inserted:' as status, COUNT(*) as count 
FROM CLOUD_COMPARE.COST_DAILY_METRICS;