# Cloud-Ops Platform Environment Configuration
# Using Oracle Autonomous Database

# Environment Settings
CLOUD_OPS_ENV=development

# API Configuration
API_HOST=0.0.0.0
API_PORT=5001

# Oracle ADB Configuration
ORACLE_HOST=adb.us-chicago-1.oraclecloud.com
ORACLE_PORT=1522
ORACLE_SERVICE=gfca71b2aacce62_photosightdb_medium.adb.oraclecloud.com
ORACLE_USER=CLOUD_COMPARE
ORACLE_PASSWORD=CloudCompare2024\!
ORACLE_WALLET_LOCATION=~/.oci/photosight_wallet2
ORACLE_WALLET_PASSWORD=gmw-gbq1rkf9jrf9WVP

# AWS Unified MCP Server
AWS_UNIFIED_URL=http://localhost:3000
AWS_UNIFIED_TIMEOUT=30

# Project Configuration
DEFAULT_PROJECT_ID=cloud-ops-prod
MONTHLY_BUDGET=10.0

# Alert Thresholds
BUDGET_WARNING_THRESHOLD=0.75
BUDGET_CRITICAL_THRESHOLD=0.90
CPU_UNDERUTILIZED_THRESHOLD=20
MEMORY_UNDERUTILIZED_THRESHOLD=30
ANOMALY_WARNING_THRESHOLD=0.6
ANOMALY_CRITICAL_THRESHOLD=0.8

# Sync Service Settings
SYNC_INTERVAL_HOURS=1
FULL_SYNC_HOUR=2
OPTIMIZATION_DAY=sunday

# Grafana Settings
GRAFANA_ORACLE_PROXY_URL=http://oracle-proxy:5002

# Notion Configuration (to be filled later)
NOTION_TOKEN=
NOTION_RESOURCES_DB_ID=
NOTION_PROJECTS_DB_ID=
NOTION_INCIDENTS_DB_ID=
NOTION_TASKS_DB_ID=

# Pipedream Webhooks (to be filled later)
PIPEDREAM_BUDGET_ALERT_URL=
PIPEDREAM_ANOMALY_DETECTION_URL=
PIPEDREAM_COST_OPTIMIZATION_URL=
PIPEDREAM_SYNC_COMPLETION_URL=

# Notification Settings (optional)
SLACK_WEBHOOK_URL=
ALERT_EMAIL=
PAGERDUTY_INTEGRATION_KEY=
