#!/usr/bin/env python3
"""
Setup Oracle ADB Schema for Cloud-Ops Platform
Creates tables and views in the CLOUD_COMPARE schema
"""

import os
import sys
import oracledb
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Oracle ADB configuration
ORACLE_USER = os.getenv('ORACLE_USER', 'CLOUD_COMPARE')
ORACLE_PASSWORD = os.getenv('ORACLE_PASSWORD')
ORACLE_DSN = os.getenv('ORACLE_SERVICE', 'photosightdb_medium')
WALLET_LOCATION = os.path.expanduser(os.getenv('ORACLE_WALLET_LOCATION', '~/.oci/photosight_wallet2'))
WALLET_PASSWORD = os.getenv('ORACLE_WALLET_PASSWORD')

def setup_oracle_client():
    """Initialize Oracle client with wallet"""
    try:
        # For python-oracledb in thin mode, we just need to set TNS_ADMIN
        os.environ['TNS_ADMIN'] = WALLET_LOCATION
        print(f"✅ Set TNS_ADMIN to: {WALLET_LOCATION}")
    except Exception as e:
        print(f"❌ Failed to set TNS_ADMIN: {e}")
        sys.exit(1)

def create_schema():
    """Create Cloud-Ops schema in Oracle ADB"""
    
    # SQL statements for schema creation
    sql_statements = [
        # Cloud Resources table
        """CREATE TABLE cloud_resources (
            resource_id VARCHAR2(256) PRIMARY KEY,
            resource_uuid VARCHAR2(256) UNIQUE NOT NULL,
            provider VARCHAR2(50) NOT NULL,
            resource_type VARCHAR2(100) NOT NULL,
            project_id VARCHAR2(100),
            owner VARCHAR2(100),
            status VARCHAR2(50) DEFAULT 'Active',
            notion_page_id VARCHAR2(100),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            tags VARCHAR2(1000)
        )""",
        
        # Cloud Metrics table
        """CREATE TABLE cloud_metrics (
            metric_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resource_id VARCHAR2(256) REFERENCES cloud_resources(resource_id),
            metric_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            cpu_usage_percent NUMBER(5,2),
            memory_usage_percent NUMBER(5,2),
            storage_used_gb NUMBER(10,2),
            network_in_gb NUMBER(10,2),
            network_out_gb NUMBER(10,2),
            cost_daily NUMBER(10,2),
            cost_monthly NUMBER(10,2),
            anomaly_score NUMBER(3,2) DEFAULT 0
        )""",
        
        # Projects table
        """CREATE TABLE projects (
            project_id VARCHAR2(100) PRIMARY KEY,
            project_name VARCHAR2(256) NOT NULL,
            description CLOB,
            budget_monthly NUMBER(10,2) DEFAULT 0,
            status VARCHAR2(50) DEFAULT 'Active',
            owner VARCHAR2(100),
            team VARCHAR2(500),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""",
        
        # Cost Optimization table
        """CREATE TABLE cost_optimizations (
            optimization_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resource_id VARCHAR2(256) REFERENCES cloud_resources(resource_id),
            optimization_type VARCHAR2(100),
            potential_savings NUMBER(10,2),
            recommendation CLOB,
            status VARCHAR2(50) DEFAULT 'Pending',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            implemented_at TIMESTAMP
        )""",
        
        # Incidents table
        """CREATE TABLE incidents (
            incident_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resource_id VARCHAR2(256) REFERENCES cloud_resources(resource_id),
            incident_type VARCHAR2(100),
            severity VARCHAR2(20),
            description CLOB,
            status VARCHAR2(50) DEFAULT 'Open',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            resolved_at TIMESTAMP,
            resolution_notes CLOB
        )""",
        
        # Create indexes
        "CREATE INDEX idx_cloud_metrics_resource ON cloud_metrics(resource_id)",
        "CREATE INDEX idx_cloud_metrics_time ON cloud_metrics(metric_time)",
        "CREATE INDEX idx_cloud_resources_provider ON cloud_resources(provider)",
        "CREATE INDEX idx_cloud_resources_project ON cloud_resources(project_id)",
        
        # Create materialized view for resource analytics
        """CREATE MATERIALIZED VIEW resource_analytics_mv
        BUILD IMMEDIATE
        REFRESH ON DEMAND
        AS
        SELECT 
            cr.resource_id,
            cr.resource_uuid,
            cr.provider,
            cr.resource_type,
            cr.project_id,
            cr.owner,
            cr.status,
            cr.notion_page_id,
            cm_latest.cpu_usage_percent,
            cm_latest.memory_usage_percent,
            cm_latest.cost_monthly,
            cm_latest.anomaly_score,
            CASE 
                WHEN cm_latest.cpu_usage_percent < 20 THEN 'Underutilized'
                WHEN cm_latest.cpu_usage_percent > 80 THEN 'High Usage'
                WHEN cm_latest.anomaly_score > 0.7 THEN 'Anomaly Detected'
                ELSE 'Normal'
            END as optimization_flag,
            CASE 
                WHEN cr.status = 'Terminated' THEN 'Terminated'
                WHEN cm_latest.anomaly_score > 0.8 THEN 'Critical'
                WHEN cm_latest.anomaly_score > 0.6 THEN 'Warning'
                WHEN cm_latest.cpu_usage_percent > 90 THEN 'High Load'
                ELSE 'Healthy'
            END as health_status,
            cm_latest.metric_time as last_metric_time
        FROM cloud_resources cr
        LEFT JOIN (
            SELECT 
                resource_id,
                cpu_usage_percent,
                memory_usage_percent,
                cost_monthly,
                anomaly_score,
                metric_time,
                ROW_NUMBER() OVER (PARTITION BY resource_id ORDER BY metric_time DESC) as rn
            FROM cloud_metrics
        ) cm_latest ON cr.resource_id = cm_latest.resource_id AND cm_latest.rn = 1""",
        
        # Create view for project analytics
        """CREATE VIEW project_analytics_v AS
        SELECT 
            p.project_id,
            p.project_name,
            p.budget_monthly,
            p.status,
            COUNT(DISTINCT cr.resource_id) as total_resources,
            COUNT(DISTINCT CASE WHEN cr.status = 'Active' THEN cr.resource_id END) as active_resources,
            COALESCE(SUM(
                CASE WHEN cr.status = 'Active' 
                THEN (SELECT cost_monthly FROM cloud_metrics cm 
                      WHERE cm.resource_id = cr.resource_id 
                      AND cm.metric_time = (SELECT MAX(metric_time) FROM cloud_metrics WHERE resource_id = cr.resource_id))
                ELSE 0 END
            ), 0) as current_monthly_cost,
            p.budget_monthly - COALESCE(SUM(
                CASE WHEN cr.status = 'Active' 
                THEN (SELECT cost_monthly FROM cloud_metrics cm 
                      WHERE cm.resource_id = cr.resource_id 
                      AND cm.metric_time = (SELECT MAX(metric_time) FROM cloud_metrics WHERE resource_id = cr.resource_id))
                ELSE 0 END
            ), 0) as budget_remaining,
            CASE 
                WHEN p.budget_monthly = 0 THEN 'No Budget'
                WHEN COALESCE(SUM(
                    CASE WHEN cr.status = 'Active' 
                    THEN (SELECT cost_monthly FROM cloud_metrics cm 
                          WHERE cm.resource_id = cr.resource_id 
                          AND cm.metric_time = (SELECT MAX(metric_time) FROM cloud_metrics WHERE resource_id = cr.resource_id))
                    ELSE 0 END
                ), 0) > p.budget_monthly THEN 'Over Budget'
                WHEN COALESCE(SUM(
                    CASE WHEN cr.status = 'Active' 
                    THEN (SELECT cost_monthly FROM cloud_metrics cm 
                          WHERE cm.resource_id = cr.resource_id 
                          AND cm.metric_time = (SELECT MAX(metric_time) FROM cloud_metrics WHERE resource_id = cr.resource_id))
                    ELSE 0 END
                ), 0) > p.budget_monthly * 0.9 THEN 'Near Limit'
                ELSE 'Within Budget'
            END as budget_status,
            COUNT(DISTINCT CASE WHEN cr.provider = 'AWS' THEN cr.resource_id END) as aws_resources,
            COUNT(DISTINCT CASE WHEN cr.provider = 'GCP' THEN cr.resource_id END) as gcp_resources,
            COUNT(DISTINCT CASE WHEN cr.provider = 'DigitalOcean' THEN cr.resource_id END) as do_resources,
            COUNT(DISTINCT CASE WHEN cr.provider = 'Edge' THEN cr.resource_id END) as edge_resources
        FROM projects p
        LEFT JOIN cloud_resources cr ON p.project_id = cr.project_id
        GROUP BY p.project_id, p.project_name, p.budget_monthly, p.status"""
    ]
    
    # Connect to Oracle ADB
    try:
        connection = oracledb.connect(
            user=ORACLE_USER,
            password=ORACLE_PASSWORD,
            dsn=ORACLE_DSN,
            config_dir=WALLET_LOCATION,
            wallet_location=WALLET_LOCATION,
            wallet_password=WALLET_PASSWORD
        )
        cursor = connection.cursor()
        print(f"✅ Connected to Oracle ADB as {ORACLE_USER}")
        
        # Create each object
        for i, sql in enumerate(sql_statements):
            try:
                # Extract object name for logging
                if 'CREATE TABLE' in sql:
                    obj_name = sql.split('CREATE TABLE')[1].split('(')[0].strip()
                    obj_type = 'Table'
                elif 'CREATE INDEX' in sql:
                    obj_name = sql.split('CREATE INDEX')[1].split(' ON')[0].strip()
                    obj_type = 'Index'
                elif 'CREATE MATERIALIZED VIEW' in sql:
                    obj_name = sql.split('CREATE MATERIALIZED VIEW')[1].split('\n')[0].strip()
                    obj_type = 'Materialized View'
                elif 'CREATE VIEW' in sql:
                    obj_name = sql.split('CREATE VIEW')[1].split(' AS')[0].strip()
                    obj_type = 'View'
                else:
                    obj_name = f"Statement {i+1}"
                    obj_type = 'SQL'
                
                cursor.execute(sql)
                print(f"✅ Created {obj_type}: {obj_name}")
                
            except Exception as e:
                if "name is already used" in str(e):
                    print(f"⚠️  {obj_type} {obj_name} already exists")
                else:
                    print(f"❌ Failed to create {obj_type} {obj_name}: {e}")
        
        # Insert sample project
        try:
            cursor.execute("""
                INSERT INTO projects (project_id, project_name, budget_monthly, status)
                VALUES (:1, :2, :3, :4)
            """, ['cloud-ops-prod', 'Cloud Operations Production', 10.0, 'Active'])
            connection.commit()
            print("✅ Created default project")
        except Exception as e:
            if "unique constraint" in str(e).lower():
                print("⚠️  Default project already exists")
            else:
                print(f"❌ Failed to create default project: {e}")
        
        # Grant permissions (if needed)
        try:
            cursor.execute(f"GRANT SELECT ON resource_analytics_mv TO {ORACLE_USER}")
            cursor.execute(f"GRANT SELECT ON project_analytics_v TO {ORACLE_USER}")
            print("✅ Granted permissions")
        except:
            pass
        
        cursor.close()
        connection.close()
        print("\n✅ Oracle ADB schema setup complete!")
        
    except Exception as e:
        print(f"❌ Failed to connect to Oracle ADB: {e}")
        sys.exit(1)

if __name__ == "__main__":
    print("🚀 Setting up Oracle ADB Schema for Cloud-Ops Platform")
    print("=" * 50)
    
    # Initialize Oracle client with wallet
    setup_oracle_client()
    
    # Create schema
    create_schema()
    
    print("\n📋 Next steps:")
    print("1. Run: python setup_production.py")
    print("2. Start the API: python app.py")
    print("3. Test: curl http://localhost:5001/health")